<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_model extends CI_Model
{

    public $table = 'presensi';
    public $id = 'id_absen';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_query()
    {
      $sql = "SELECT a.id_absen,b.id_komunitas,b.nama_komunitas,a.tgl,a.jam_msk,a.jam_klr,c.nama_khd,d.nama_status,d.id_status
              FROM presensi as a,komunitas as b,kehadiran as c,stts as d
              WHERE a.id_komunitas=b.id_komunitas
              AND c.id_khd=a.id_khd
              AND d.id_status=a.id_status";
      return $this->db->query($sql)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_absen', $q);
      	$this->db->or_like('id_komunitas', $q);
      	$this->db->or_like('tgl', $q);
      	$this->db->or_like('jam_msk', $q);
      	$this->db->or_like('jam_klr', $q);
      	$this->db->or_like('id_khd', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_absen', $q);
      	$this->db->or_like('id_komunitas', $q);
      	$this->db->or_like('tgl', $q);
      	$this->db->or_like('jam_msk', $q);
      	$this->db->or_like('jam_klr', $q);
      	$this->db->or_like('id_khd', $q);
      	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

function sort_tgl()
    {
        $tgl_mulai = $this->input->post('startdate');
        $tgl_akhir = $this->input->post('enddate');


        // $this->db->select('*');
        // $this->db->from('presensi');
        // $this->db->join('komunitas', 'id_komunitas = id_komunitas');
        // $this->db->where('tgl >= ',$tgl_mulai);
        // $this->db->where('tgl <= ',$tgl_akhir);
        // $query = $this->db->get();
        // return $query->result();

         $sql = "SELECT a.id_absen,b.id_komunitas,b.nama_komunitas,a.tgl,a.jam_msk,a.jam_klr,c.nama_khd,d.nama_status,d.id_status
              FROM presensi as a,komunitas as b,kehadiran as c,stts as d
              WHERE a.id_komunitas=b.id_komunitas
              AND c.id_khd=a.id_khd
              AND d.id_status=a.id_status
              AND a.tgl>='$tgl_mulai'
              AND a.tgl<='$tgl_akhir'";
        return $this->db->query($sql)->result();

    }

}

/* End of file Presensi_model.php */
/* Location: ./application/models/Presensi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-03 13:03:02 */
/* http://harviacode.com */
